# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_inventory:
            contexts_as_services:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.shared_storage
                - sylius.behat.context.transform.product

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product

                - sylius.behat.context.ui.shop.product
                - sylius.behat.context.ui.shop.cart

            filters:
                tags: "@inventory && @ui"
